rsksmart/rif-relay

contracts/RelayHub.sol
contracts/factory/IProxyFactory.sol
contracts/factory/ProxyFactory.sol
contracts/forwarder/IForwarder.sol
contracts/forwarder/SmartWallet.sol
contracts/interfaces/IRelayHub.sol
contracts/utils/GsnEip712Library.sol
src/common/EIP712/ForwardRequest.ts
src/common/EIP712/TypedRequestData.ts
src/relayclient/RelayClient.ts
src/relayclient/RelayProvider.ts
src/relayclient/types/GsnTransactionDetails.ts
src/relayclient/types/RelayTransactionRequest.ts
src/relayserver/HttpServer.ts
src/relayserver/RelayServer.ts
test/GsnTestEnvironment.test.ts
test/PaymasterCommitment.test.ts
test/ProxyFactory.test.ts
test/RelayHub.test.ts
test/RelayHubGasCalculations.test.ts
test/RelayHubPenalizations.test.ts
test/StakeManager.test.ts
test/TestUtils.ts
test/Utils.test.ts
test/relayclient/AccountManager.test.ts
test/relayclient/KnownRelaysManager.test.ts
test/relayclient/RelayClient.test.ts
test/relayclient/RelayProvider.test.ts
test/relayclient/RelaySelectionManager.test.ts
test/smartwallet/SmartWallet.test.ts

Added index and recoverer to the smart wallet creation to be compatible with Gasless token. Also, Smart Wallet now stores keccak256(ownerEOA) instead of just ownerEOA

Sw new address fields

---

contracts/factory/IProxyFactory.sol
contracts/factory/ProxyFactory.sol
src/relayclient/RelayProvider.ts
test/relayclient/RelayProvider.test.ts

Helper functions to deploy smart wallet and calculate smart wallet address

Helper functions 

---

.circleci/config.yml
rsknode/node.conf

Adding configuration for CircleCI integration. Each build (commit,merge) will trigger the execution of the test suites against an RSKj regtest node.

Circle ci setup

---

test/VersionRegistry.test.ts

Delta difference to account for execution with CircleCI

Increased version registry delta time for RSK

---

.circleci/config.yml

Defined parallel jobs and reusable commands to reduce overall workflow duration at CircleCI

Ci parallelization

---

README.md
truffle.js

Changed network id for the correct ones. Also updated the addresses of the latest deployed contracts including their link to the explorer.

Truffle fix

---

README.md
package.json
yarn.lock

Fix packages

---

contracts/Penalizer.sol
contracts/StakeManager.sol
contracts/test/PayableWithEmit.sol
test/common/VersionManager.test.ts

Minor modifications to have all contracts with the same version (2.0.1).

Modified contracts version to match project version

---

contracts/forwarder/SmartWallet.sol
test/ProxyFactory.test.ts
test/relayserver/TransactionManager.test.ts

Small change in SW to avoid unwanted re-entrancy attacks when calling external contracts.

Small change in SW to avoid unwanted re-entrancy attacks

---

README.md
src/cli/CommandsLogic.ts
src/common/Utils.ts
src/relayclient/ContractInteractor.ts
src/relayclient/HttpWrapper.ts
src/relayclient/RelayClient.ts
src/relayserver/RegistrationManager.ts

First commit fixes _getPastEvents so the list of topics is properly built
Second commit adds small fixes so the Client is compatible with web-based dApps.

Dapp compatibility fixes

---

package.json

package.json file updated with Enveloping information

Updated package.json for Enveloping

---

README.md
contracts/Penalizer.sol
contracts/RelayHub.sol
contracts/StakeManager.sol
contracts/factory/ProxyFactory.sol
contracts/paymaster/BasePaymaster.sol
contracts/utils/VersionRegistry.sol

Added selfdestruct and pausable support for contracts to do an initial deployment on Mainnet. 
Added limits to staking in StakeManager and to funds in RelayHub
Added version 1 description to README.md

Prepare v1 tag

---

contracts/paymaster/BasePaymaster.sol

Commented import for support of kill functionality in V1

Added comment for V1

---

docs/basic_requirements.md
docs/development_guide.md
docs/enveloping_architecture.md
docs/integration_guide.md
docs/launching_enveloping.md
docs/overhead_tx_costs.md

Mostly minor edits. The one that needs the most attention is the *integration_guide*. I am not making suggestions (in this round) to that one because it can change the meaning.

Readme review

---

docs/integration_guide.md
run-tests.sh
scripts/postpack
scripts/prepublish
src/common/Utils.ts
src/relayclient/Configurator.ts
src/relayclient/RelayClient.ts
test/EnvelopingUtils.test.ts
test/Flows.test.ts
test/TestUtils.ts
test/relayclient/KnownRelaysManager.test.ts
test/relayclient/RelayClient.test.ts
test/relayclient/RelayProvider.test.ts

The pull request added to the project Enveloping Utils.
It is a simplification for the process to deploy a smart wallet and also to relay a transaction.  The utility is in `Utils.ts` and it's already tested.

Enveloping Utils

---

src/relayclient/TestEnvironment.ts
test/EnvelopingUtils.test.ts
test/relayclient/RelayClient.test.ts
test/relayclient/SmartWalletDiscovery.test.ts

Small fixes, that may impact in the future if we upgrade typescript

Fixes to be compatible with newer typescript versions

---

.circleci/config.yml
README.md
contracts/RelayHub.sol
contracts/interfaces/IRelayHub.sol
docs/pr_128_changelog.md
migrations/2_deploy_contracts.js
src/cli/CommandsLogic.ts
src/common/Environments.ts
src/relayclient/Enveloping.ts
src/relayclient/types/RelayHubConfiguration.ts
test/RelayHubRegistrationsManagement.test.ts
test/StakeManagement.test.ts
test/TestUtils.ts
test/relayserver/RegistrationManager.test.ts

unused gasOverhead field removed from RelayHub, readme Updated

---

README.md

This PR updates the Readme with the new testnet contract addresses recently deployed.

Updating Readme with the new contract addresses

---

.circleci/config.yml
docker/docker-compose.yml
scripts/test
scripts/utils.sh

Remove code duplication and unify test among CI and local execution.
Create some bash utility functions to be called by external scripts.

PP 49 - Unify tests

---

.circleci/config.yml
package.json
rsknode/Dockerfile
run-tests.sh
test/EnvelopingUtils.test.ts
test/TestUtils.ts
test/relayclient/RelayProvider.test.ts
test/relayclient/SmartWalletDiscovery.test.ts

- Change RSKj docker container to expose websocket port
- Retrieve hostname from the current provider to create the websocket provider.

PP-97: Fix websocket configuration on docker tests

---

.circleci/config.yml
package-lock.json
scripts/utils.sh
test/TestUtils.ts

- Fix the execution of the tests against docker since that it was using the first file specified as test name, so that file was skipped from the test execution.
-  Wrap the deletion of the temporary folder `'/tmp/enveloping/test/server'` in a try/catch to avoid errors on MacOs

PP-103: fix missing folder on tests [develop]

---

package-lock.json
scripts/utils.sh
test/TestUtils.ts

- Update package-lock.json
- Fix the execution of test against docker since that it was using the first file specified as test name, so that file was skipped from the test execution.
-  Wrap the deletion of the temporary folder `'/tmp/enveloping/test/server'` in a try/catch to avoid errors on MacOs

PP-103: fix missing folder during test execution on MacOS

---

test/GasAttacks.test.ts
test/RelayHub.test.ts
test/RelayHubPenalizations.test.ts
test/TestUtils.ts
test/Utils.test.ts
test/Verifiers.test.ts
test/WalletFactory.test.ts
test/relayclient/AccountManager.test.ts
test/relayclient/Configurator.test.ts
test/relayclient/RelayClient.test.ts
test/relayserver/RelayServer.test.ts
test/smartwallet/CustomSmartWallet.test.ts
test/smartwallet/SmartWallet.test.ts

Modify some tests in order to avoid passing the domain separator as part of the request.
This extra and unnecessary field makes the operation more expensive.
https://rsklabs.atlassian.net/browse/PP-137

PP-137/Unnecessary domainSeparator field in Request

---

.circleci/config.yml
package-lock.json
package.json
scripts/test
test/relayclient/Configurator.test.ts

Fix the test related to Configurator

PP-274: Fix configurator test

---

test/RelayHub.test.ts
test/RelayHubGas.test.ts

Migration of tests from truffle to hardhat/ethers
Part of the ethers migration project

PP-637: relay hub gas consumption tests

---

package-lock.json
package.json
test/relayserver/RegistrationManager.test.ts
test/relayserver/RelayServer.test.ts
test/relayserver/TransactionManager.test.ts
test/relayserver/TxStoreManager.test.ts

- fix broken tests
- include tests to cover server fixes
- the tests were broken due to some changes in the server
- the tests don't cover a bug we recently found

PP-842: fix underpriced transactions

---

Readme.md

- The guide includes the process to get started with the RIF Relay Sample dApp SDK.
- The purpose of these changes is to facilitate developers and users in effectively utilizing the RIF Relay
- The guide aims to lower the entry barrier for new users and enhance the understanding of the SDK’s capabilities.
- (optional: include links to other issues, PRs, tickets, etc)

Get started guide for RIF Relay Sample dApp SDK

---

test/relayserver/RelayServer.test.ts

test: fix failing tests due to balance
